
import sys,os

# function call
# kw={"x":1}
# generate_id(**kw,a=2,b=2)
def generate_id(**kwargs):
    # parameters usage
    # print(kwargs)  # 参数接收{'x': 1, 'a': 2, 'b': 2}
    # print(kwargs['x'])  # 参数读取
    
    # Required parameters
    kw1='name'
    name=kwargs[kw1].replace(".","_")
    kw2='version'
    version=kwargs[kw2].replace(".","_")

    # generate id
    import uuid
    import time
    id_time=int(round(time.time() * 1000000))
    # print(id_time)
    id_uuid=str(uuid.uuid1()).replace("-","")  #  generated by MAC address, current timestamp, and random number
    # print(id_name)
    id="func-{}-{}-{}-{}".format(name,id_time,id_uuid,version)

    return id


def create_node(**kwargs):
    # Required parameters
    id=generate_id(**kwargs)
    
    # copy example and rename
    import shutil
    shutil.copy("cli/lib/flowfunction/func-node-example-file.py",'lib/flowfunction/{}.py'.format(id))


if __name__=='__main__':
    print("CLI start...")
    create_node(name="test01",version="0.0.1")

    







