
import sys
import os


def generate_id(name, version):
    name = name.replace(".", "_")
    version = version.replace(".", "_")

    # generate id
    import uuid
    import time
    id_time = int(round(time.time() * 1000000))
    # print(id_time)
    # generated by MAC address, current timestamp, and random number
    id_uuid = str(uuid.uuid1()).replace("-", "")
    # print(id_name)
    id = "func-{}-{}-{}-{}".format(name, id_time, id_uuid, version)

    return id


def create_custom_node(name, version, node_path):
    # Required parameters
    id = generate_id(name, version)

    # copy example and rename
    import shutil
    shutil.copy(os.path.join(sys.path[0], __file__.replace(".py", ""), "func-node-example.py"),
                os.path.join(node_path, "{}.py".format(id)))


if __name__ == '__main__':
    print("CLI start...")
    create_custom_node(name="test", version="0.0.1",node_path=os.path.join(sys.path[0],"../../lib/flowfunction"))
